<a href="https://colab.research.google.com/github/LowRands/Machine-Learning-with-python/blob/main/Campus_Dataset_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Campus Dataset Project
Ethan Lourens

## Data Preparation
This section loads the campus dataset and prepares it for analysis

In [1]:
import pandas as pd

### Load the dataset

In [2]:
df = pd.read_excel(
    '/content/drive/MyDrive/Colab Notebooks/CampusWalkDataset_TemplateIDs.xlsx',
    sheet_name=0, #reading the first sheet from the excel spreadsheet
    skiprows = 4) #skipping the first 4 rows because they are blank

In [3]:
#display(df)

In [4]:
#df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/CampusWalkDataset.csv',
   # skiprows=4,
#)

In [5]:
#pd.set_option('display.max_columns', None)
##pd.set_option('display.max_rows', None)
#pd.set_option('display.max_colwidth', None)

#display(df)

In [6]:
print(df.isnull().sum()) # Checking each catergory for no entries, adding them up and displaying the amount per category

recorder_id                                0
date                                      64
location                                  64
weather                                   64
temperature_c                             64
sound level                               64
foot_traffic                              64
primary_sound_type_urban                  64
other_sound_type_urban                    67
primary_sound_type_nature                 64
other_sound_type_nature                   66
insects_count                             64
birds_count                               64
trees_presence                            69
native_or_wild_plant_presence             76
ornnamental_or_planted_plant_presence    102
moss_or_lichen_presence                  100
wellbeing_rating                          64
ease_rating                               64
stress_rating                             64
nature_connection_experience_rating       64
most_notable_nature_element               79
other_notes                              132
dtype: int64

In [7]:
df = df.dropna(
    subset=df.columns.difference(['recorder_id']),
    how='all'
) # deletes the rows that has no entries other than recorder id

In [8]:
duplicates = df.duplicated().sum()
print("Exact duplicate rows:", duplicates) # deletes all rows that have the exact same rows

Exact duplicate rows: 0

In [9]:
print("Rows:", len(df))
print("Missing values:", df.isnull().sum().sum())
print("Duplicate rows:", df.duplicated().sum())

Rows: 135
Missing values: 179
Duplicate rows: 0

# Cleaning up the Dates
This code converts the entries in the date column from their original format (like strings or mixed types) into standardized pandas datetime objects (YYYY-MM-DD).

The errors="coerce" parameter ensures that if there are any invalid dates, corrupt texts, or empty values, pandas will gracefully convert them to NaT (Not a Time/null values) instead of crashing with an error.

In [10]:
df.date = pd.to_datetime(
    df.date,
    errors="coerce"
)
display(df.date)

0     2026-09-22
1     2026-09-22
2     2026-09-22
3     2026-09-22
4     2026-09-22
         ...
133   2026-09-23
134   2026-10-07
135   2026-10-07
136   2026-10-07
137   2026-10-07
Name: date, Length: 135, dtype: datetime64[ns]

# Cleaning up the Weather column
- Changing the weather column to all have the same formatting
- Having each word start with a capital, so (**partly cloudy**) changes to (**Partly Cloudy**) and (**sunny**) changes to (**Sunny**)

In [11]:
# "str" converts the entire column to strings and "title" converts every string to *Title Case*, the first letter of every word is capitalised
df.weather = df.weather.str.title()
display(df.weather)

0      Partly Cloudy
1              Sunny
2      Partly Cloudy
3      Partly Cloudy
4              Sunny
           ...
133            Windy
134            Windy
135            Windy
136    Partly Cloudy
137            Windy
Name: weather, Length: 135, dtype: object

In [12]:
# looks for weather that is outside the valid weather array.
valid_weather = [
    "Sunny",
    "Partly Cloudy",
    "Cloudy",
    "Windy",
    "Raining"
]

invalid = df[~df["weather"].isin(valid_weather)]
print(invalid[["weather"]])

Empty DataFrame
Columns: [weather]
Index: []

In [13]:
weather_mapping = {
    'Sunny': 0,
    'Partly Cloudy': 1,
    'Cloudy': 2,
    'Windy': 3,
    'Raining': 4
}

df['Weather_mapping_encoded'] = df['weather'].map(weather_mapping)
print("Mapping Verification")
print(df[['weather', 'Weather_mapping_encoded']].drop_duplicates().reset_index(drop=True))

Mapping Verification
         weather  Weather_mapping_encoded
0  Partly Cloudy                        1
1          Sunny                        0
2          Windy                        3
3         Cloudy                        2

# Cleaning up the Temperature Column
- I am changing the entire temperature column to all have the same formatting
- All Temperature is in Celcuis  $(^\circ\mathrm{C})$

In [14]:
# Clean any duplicate 'C', '°', or '°C' characters from the temperature column, then format uniformly
df['temperature_c'] = (
    df['temperature_c']
    .astype(str)
    .str.replace('°C', '', regex=False)
    .str.replace('°', '', regex=False)
    .str.replace('C', '', regex=False)
    .str.strip()
)
# Re-apply uniform format for non-null/non-NaN entries
df['temperature_c'] = df['temperature_c'].apply(
    lambda x: f"{x}°C" if pd.notnull(x) and x != 'nan' and x != '' else None
)
display(df.temperature_c)

0      16°C
1      16°C
2      16°C
3      16°C
4      16°C
       ...
133    16°C
134    10°C
135    10°C
136    15°C
137    10°C
Name: temperature_c, Length: 135, dtype: object

# Cleaning the Bird and Insect count columns
- Makes the bird/insect numbers into integers instead of floats
- Checks if any of the bird/insect inputted data is invalid/negative numbers

In [15]:
df['birds_count'] = df['birds_count'].astype('Int64')
df['insects_count'] = df['insects_count'].astype('Int64')

print(df["birds_count"].describe())
print(df["insects_count"].describe())

count       135.0
mean     1.992593
std      2.789897
min           0.0
25%           0.0
50%           1.0
75%           3.0
max          20.0
Name: birds_count, dtype: Float64
count       135.0
mean     2.733333
std      5.106624
min           0.0
25%           0.0
50%           1.0
75%           3.0
max          31.0
Name: insects_count, dtype: Float64

In [16]:
# checks if bird and insect values are less than 0/invalid
invalid_birds = df[df["birds_count"] < 0]
print(invalid_birds)
invalid_insects = df[df["insects_count"] < 0]
print(invalid_insects)

Empty DataFrame
Columns: [recorder_id, date, location, weather, temperature_c, sound level, foot_traffic, primary_sound_type_urban, other_sound_type_urban, primary_sound_type_nature, other_sound_type_nature, insects_count, birds_count, trees_presence, native_or_wild_plant_presence, ornnamental_or_planted_plant_presence, moss_or_lichen_presence, wellbeing_rating, ease_rating, stress_rating, nature_connection_experience_rating, most_notable_nature_element, other_notes, Weather_mapping_encoded]
Index: []

[0 rows x 24 columns]
Empty DataFrame
Columns: [recorder_id, date, location, weather, temperature_c, sound level, foot_traffic, primary_sound_type_urban, other_sound_type_urban, primary_sound_type_nature, other_sound_type_nature, insects_count, birds_count, trees_presence, native_or_wild_plant_presence, ornnamental_or_planted_plant_presence, moss_or_lichen_presence, wellbeing_rating, ease_rating, stress_rating, nature_connection_experience_rating, most_notable_nature_element, other_notes, Weather_mapping_encoded]
Index: []

[0 rows x 24 columns]

# Cleaning the sound column
- Define a dictionary that maps each ordinal category to a numeric value where Quiet becomes 0, Moderate becomes 1, and Loud becomes 2 (preserving the order of intensity).

In [17]:
sound_mapping = {
    'Quiet': 0,
    'Moderate': 1,
    'Loud': 2
}

df['Sound_level_encoded'] = df['sound level'].map(sound_mapping)
print("Mapping Verification")
print(df[['sound level', 'Sound_level_encoded']].drop_duplicates().reset_index(drop=True))

Mapping Verification
  sound level  Sound_level_encoded
0       Quiet                    0
1    Moderate                    1
2        Loud                    2

In [18]:
# Map null/NaN values to 0 while keeping the original note text intact
df['Other_notes_encoded'] = df['other_notes'].fillna(0)

print("Mapping Verification")
print(df[['other_notes', 'Other_notes_encoded']].drop_duplicates().reset_index(drop=True))

Mapping Verification
                                          other_notes  \
0                                                 NaN
1                                    Football in Bush
2                                           Generator
3                                               Trash
4                                           Ambulance
5                             A soft yellow golf ball
6                                      People smoking
7                      Bags left outside library wall
8                                  Loud traffic noise
9                              Lots of dumped clothes
10                                    Yellow Golfball
11                                            Smoking
12                                            pathway
13                                           gunshots
14                                  Construction site
15                                             People
16                                             gardai
17                                              fumes
18                        chair noises in sports hall
19                                          machinery
20                        Traffic Volume highest here
21          Teleporter and lots of cars (Parking lot)
22                                      a lot of wasp
23                                 rocks on the floor
24                                     a telehandler
25                               Berries on the bush
26                Patio made for sitting and relaxing
27                     Lot of people nd olice station
28                             Lots of smokers/vapers
29                                     No one around
30                                   Ants on my sheet
31                            Lots of webs no spiders
32                Big tele handler with extended Boom
33                    trash/cloths near the wall area
34  very sour apples growing on the tree advised n...
35               telehandler parked close by eye sore
36                          Quiet chatter in distance
37                                       Lost clothes
38                          Can see urban enviroments
39                  Can hear planes/ fork lift nearby
40                         Helicopter passed overhead
41                            Cold Breeze, Light Wind
42                   Away from Foot Traffic, Peaceful
43                      Buildings blocking the breeze
44                           clothes were by the tree
45                                    crab apple tree
46                              Noted service machine
47                            Students more prevalent
48                                              Bench
49                                   Full parking lot
50                                   Small apple tree
51                                            smoking
52                                             tissue
53                                                dog
54                                       walking path
55                                               cars
56                          An insect was on my paper
57                           The parking is very full
58                 There are clothes left near a tree

                                  Other_notes_encoded
0                                                   0
1                                    Football in Bush
2                                           Generator
3                                               Trash
4                                           Ambulance
5                             A soft yellow golf ball
6                                      People smoking
7                      Bags left outside library wall
8                                  Loud traffic noise
9                              Lots of dumped clothes
10                                    Yellow Golfball
11                                            Smoking
12                                            pathway
13                                           gunshots
14                                  Construction site
15                                             People
16                                             gardai
17                                              fumes
18                        chair noises in sports hall
19                                          machinery
20                        Traffic Volume highest here
21          Teleporter and lots of cars (Parking lot)
22                                      a lot of wasp
23                                 rocks on the floor
24                                     a telehandler
25                               Berries on the bush
26                Patio made for sitting and relaxing
27                     Lot of people nd olice station
28                             Lots of smokers/vapers
29                                     No one around
30                                   Ants on my sheet
31                            Lots of webs no spiders
32                Big tele handler with extended Boom
33                    trash/cloths near the wall area
34  very sour apples growing on the tree advised n...
35               telehandler parked close by eye sore
36                          Quiet chatter in distance
37                                       Lost clothes
38                          Can see urban enviroments
39                  Can hear planes/ fork lift nearby
40                         Helicopter passed overhead
41                            Cold Breeze, Light Wind
42                   Away from Foot Traffic, Peaceful
43                      Buildings blocking the breeze
44                           clothes were by the tree
45                                    crab apple tree
46                              Noted service machine
47                            Students more prevalent
48                                              Bench
49                                   Full parking lot
50                                   Small apple tree
51                                            smoking
52                                             tissue
53                                                dog
54                                       walking path
55                                               cars
56                          An insect was on my paper
57                           The parking is very full
58                 There are clothes left near a tree

In [19]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

display(df)

,recorder_id,date,location,weather,temperature_c,sound level,foot_traffic,primary_sound_type_urban,other_sound_type_urban,primary_sound_type_nature,other_sound_type_nature,insects_count,birds_count,trees_presence,native_or_wild_plant_presence,ornnamental_or_planted_plant_presence,moss_or_lichen_presence,wellbeing_rating,ease_rating,stress_rating,nature_connection_experience_rating,most_notable_nature_element,other_notes,Weather_mapping_encoded,Sound_level_encoded,Other_notes_encoded
0,R26_001,2026-09-22,L01 MainEntrance,Partly Cloudy,16°C,Quiet,Low,Human voices,Traffic,Wind,Trees,0,1,Many,Some,Some,Some,Positive wellbeing,Neutral,Stressful,Less connected,Plants and trees,NaN,1,0,0
1,R26_001,2026-09-22,L02 LibraryGreen,Sunny,16°C,Moderate,Low,Traffic,Human voices,Wind,Trees,0,2,Many,NaN,Some,NaN,Positive wellbeing,Neutral,Neutral,A little more connected,Sunrays on grass,NaN,0,1,0
2,R26_001,2026-09-22,L06 HedgingBehindSportsCentre,Partly Cloudy,16°C,Quiet,Low,Construction,Traffic,Wind,Other birds,10,20,Many,NaN,Many,Some,Positive wellbeing,Easy,Mostly calm,No change,Very quiet,NaN,1,0,0
3,R26_001,2026-09-22,L08 AccessRoadNearSportsCentre,Partly Cloudy,16°C,Moderate,Low,Human voices,Human voices,Wind,Other birds,0,2,One or two,Some,NaN,Some,Positive wellbeing,Neutral,Neutral,Much more connected,Harsh wind,NaN,1,1,0
4,R26_001,2026-09-22,L06 HedgingBehindSportsCentre,Sunny,16°C,Moderate,Low,Traffic,Other,Wind,Trees,0,0,One or two,NaN,Some,NaN,Positive wellbeing,Easy,Mostly calm,Less connected,Crowded area,NaN,0,1,0
5,R26_002,2026-09-22,L01 MainEntrance,Sunny,17°C,Moderate,Low,Traffic,Human voices,Other birds,Insects,2,4,Many,Some,Some,Many,Positive wellbeing,Easy,Mostly calm,A little more connected,trees,Football in Bush,0,1,Football in Bush
6,R26_002,2026-09-22,L04 PathFrontiHub,Windy,17°C,Moderate,Low,Traffic,Other,Wind,Insects,2,2,Many,Some,Many,Some,Neutral,Neutral,Very calm,No change,plants and trees,NaN,3,1,0
7,R26_002,2026-09-22,L05 GreenFrontSportsCentre,Sunny,19°C,Moderate,Low,Traffic,Service machinery,Wind,Other,7,0,Many,Many,Many,Many,Positive wellbeing,Vey easy,Mostly calm,Much more connected,wild plants,NaN,0,1,0
8,R26_002,2026-09-22,L06 HedgingBehindSportsCentre,Cloudy,16°C,Quiet,Low,Traffic,Human voices,Wind,Trees,3,1,Many,Many,Many,Some,Neutral,Neutral,Very calm,Less connected,shaded area,NaN,2,0,0
9,R26_002,2026-09-22,L07 CarParkNearSportsCentre,Sunny,18°C,Quiet,Low,Service machinery,Traffic,Other birds,Trees,6,2,Many,Many,Many,Some,Very positive wellbeing,Vey easy,Very calm,Much more connected,insects,NaN,0,0,0
10,R26_003,2026-09-22,L01 MainEntrance,Sunny,18°C,Moderate,Low,Traffic,Human voices,Other birds,Wind,1,4,Many,Some,Some,Many,Positive wellbeing,Easy,Mostly calm,A little more connected,trees,Football in Bush,0,1,Football in Bush
11,R26_003,2026-09-22,L04 PathFrontiHub,Sunny,17°C,Moderate,Low,Traffic,Other,Wind,Insects,2,2,Many,Some,Many,Some,Very positive wellbeing,Easy,Mostly calm,Much more connected,The Plants,NaN,0,1,0
12,R26_003,2026-09-22,L05 GreenFrontSportsCentre,Sunny,18°C,Moderate,Moderate,Traffic,Service machinery,Wind,Insects,7,1,Many,Many,Many,Many,Positive wellbeing,Easy,Mostly calm,A little more connected,The Wild Plants,NaN,0,1,0
13,R26_003,2026-09-22,L06 HedgingBehindSportsCentre,Cloudy,16°C,Quiet,Low,Traffic,Human voices,Wind,Trees,3,1,Many,Many,Many,Some,Neutral,Neutral,Neutral,Less connected,Shaded area,NaN,2,0,0
14,R26_003,2026-09-22,L07 CarParkNearSportsCentre,Sunny,18°C,Quiet,Low,Service machinery,Traffic,Trees,Insects,5,2,Many,Some,Many,Some,Very positive wellbeing,Vey easy,Very calm,Much more connected,Insects,NaN,0,0,0
15,R26_004,2026-09-22,L04 PathFrontiHub,Sunny,17°C,Moderate,Low,Traffic,Other,Wind,Insects,2,2,Many,Some,Many,Some,Very positive wellbeing,Vey easy,Very calm,Much more connected,Plants,NaN,0,1,0
16,R26_004,2026-09-22,L06 HedgingBehindSportsCentre,Sunny,16°C,Quiet,Low,Traffic,Human voices,Wind,Trees,3,1,Many,Many,Many,Some,Neutral,Neutral,Neutral,Less connected,Shaded area,NaN,0,0,0
17,R26_004,2026-09-22,L01 MainEntrance,Sunny,17°C,Moderate,Low,Traffic,Human voices,Other birds,Wind,1,4,One or two,Some,Some,Many,Very positive wellbeing,Vey easy,Very calm,Much more connected,Trees,NaN,0,1,0
18,R26_004,2026-09-22,L05 GreenFrontSportsCentre,Sunny,19°C,Moderate,Low,Traffic,Human voices,Wind,Insects,1,0,Many,Many,Many,Many,Very positive wellbeing,Vey easy,Very calm,Much more connected,Reddish plants,NaN,0,1,0
19,R26_004,2026-09-22,L02 LibraryGreen,Sunny,18°C,Quiet,Low,Service machinery,Traffic,Trees,Insects,5,2,Many,Some,Some,Some,Very positive wellbeing,Vey easy,Very calm,Much more connected,Insects,NaN,0,0,0
20,R26_005,2026-09-22,L01 MainEntrance,Sunny,16°C,Moderate,Low,Traffic,Human voices,Wind,Trees,0,1,Many,Some,Some,Many,Neutral,Neutral,Neutral,No change,The wind,NaN,0,1,0
21,R26_005,2026-09-22,L02 LibraryGreen,Sunny,16°C,Quiet,Low,Traffic,Human voices,Trees,Insects,1,0,Many,Some,Many,NaN,Very positive wellbeing,Vey easy,Very calm,Much more connected,Leaves falling,NaN,0,0,0
22,R26_005,2026-09-22,L04 PathFrontiHub,Sunny,16°C,Moderate,Low,Traffic,Human voices,Wind,Other,0,3,Many,Some,Some,NaN,Very low wellbeing,Very uneasy,Very stressful,No change,Faint music from car,NaN,0,1,0
23,R26_005,2026-09-22,L05 GreenFrontSportsCentre,Sunny,15°C,Quiet,Low,Other,Human voices,Trees,Other birds,0,2,Many,Many,Many,Some,Low wellbeing,Vey easy,Mostly calm,Much more connected,Quiet,NaN,0,0,0
24,R26_005,2026-09-22,L06 HedgingBehindSportsCentre,Sunny,16°C,Quiet,Low,Construction,Traffic,Seagulls,Other birds,2,4,Many,Many,Some,Some,Low wellbeing,Slighly uneasy,Mostly calm,No change,Seaguls,NaN,0,0,0
25,R26_006,2026-09-22,L01 MainEntrance,Partly Cloudy,16°C,Moderate,Moderate,Human voices,Traffic,Wind,Other birds,0,0,Many,NaN,Some,Some,Low wellbeing,Slighly uneasy,Stressful,Less connected,Trees,NaN,1,1,0
26,R26_006,2026-09-22,L02 LibraryGreen,Partly Cloudy,16°C,Moderate,Low,Traffic,Human voices,Other birds,Wind,5,2,Many,NaN,NaN,NaN,Neutral,Easy,Neutral,A little more connected,Grass,NaN,1,1,0
27,R26_006,2026-09-22,L06 HedgingBehindSportsCentre,Partly Cloudy,16°C,Quiet,Low,Construction,Traffic,Other birds,Wind,2,12,One or two,NaN,Some,Some,Positive wellbeing,Neutral,Mostly calm,A little more connected,Plants,NaN,1,0,0
28,R26_006,2026-09-22,L07 CarParkNearSportsCentre,Sunny,16°C,Quiet,Low,Construction,Traffic,Wind,Trees,0,1,One or two,Some,NaN,Some,Very low wellbeing,Slighly uneasy,Stressful,Less connected,lawn,NaN,0,0,0
29,R26_006,2026-09-22,L08 AccessRoadNearSportsCentre,Partly Cloudy,16°C,Moderate,Low,Traffic,Other,Wind,Other birds,0,0,One or two,NaN,Some,Some,Low wellbeing,Neutral,Mostly calm,No change,Tree,Generator,1,1,Generator
30,R26_007,2026-09-22,L01 MainEntrance,Partly Cloudy,17°C,Moderate,High,Human voices,Traffic,Trees,Other birds,3,4,Many,Some,Many,Some,Neutral,Slighly uneasy,Stressful,No change,Wind,NaN,1,1,0
31,R26_007,2026-09-22,L03 LowerSidePathiHub,Cloudy,16°C,Moderate,Low,Traffic,Human voices,Other birds,Insects,3,1,One or two,Some,NaN,Many,Positive wellbeing,Neutral,Mostly calm,No change,NaN,Trash,2,1,Trash
32,R26_007,2026-09-22,L04 PathFrontiHub,Sunny,17°C,Loud,Moderate,Traffic,Human voices,Other birds,Wind,3,1,One or two,Some,Some,Some,Neutral,Slighly uneasy,Mostly calm,No change,Wind,Ambulance,0,2,Ambulance
33,R26_007,2026-09-22,L06 HedgingBehindSportsCentre,Cloudy,15°C,Quiet,Moderate,Traffic,Construction,Trees,Other birds,31,12,Many,Some,Many,Many,Positive wellbeing,Easy,Mostly calm,No change,Snails on wall,NaN,2,0,0
34,R26_007,2026-09-22,L08 AccessRoadNearSportsCentre,Partly Cloudy,16°C,Quiet,Low,Traffic,Other,Wind,Other birds,4,1,One or two,Some,Some,Many,Neutral,Slighly uneasy,Neutral,No change,Tweeting Birds,NaN,1,0,0
35,R26_008,2026-09-22,L01 MainEntrance,Partly Cloudy,16°C,Moderate,Moderate,Human voices,Traffic,Wind,Wind,1,3,Many,Some,NaN,Some,Positive wellbeing,Neutral,Mostly calm,A little more connected,Sunny,NaN,1,1,0
36,R26_008,2026-09-22,L03 LowerSidePathiHub,Partly Cloudy,16°C,Moderate,Low,Traffic,Traffic,Trees,Wind,0,3,Many,Many,NaN,Many,Positive wellbeing,Easy,Mostly calm,A little more connected,Quiet,NaN,1,1,0
37,R26_008,2026-09-22,L08 AccessRoadNearSportsCentre,Partly Cloudy,16°C,Quiet,Low,Service machinery,Traffic,Wind,Other birds,3,3,One or two,Some,Some,Some,Positive wellbeing,Easy,Mostly calm,A little more connected,NaN,NaN,1,0,0
38,R26_008,2026-09-22,L06 HedgingBehindSportsCentre,Partly Cloudy,16°C,Quiet,Low,Human voices,Human voices,Wind,Trees,26,13,Many,Some,Some,Some,Positive wellbeing,Easy,Mostly calm,A little more connected,NaN,A soft yellow golf ball,1,0,A soft yellow golf ball
39,R26_008,2026-09-22,L04 PathFrontiHub,Partly Cloudy,16°C,Moderate,Moderate,Traffic,Other,Wind,Wind,1,3,Many,Some,Some,NaN,Positive wellbeing,Easy,Mostly calm,A little more connected,NaN,NaN,1,1,0
40,R26_009,2026-09-22,L01 MainEntrance,Sunny,16°C,Moderate,Moderate,Human voices,Traffic,Trees,Other birds,1,3,Many,Some,Many,Some,Positive wellbeing,Neutral,Mostly calm,A little more connected,Barren,People smoking,0,1,People smoking
41,R26_009,2026-09-22,L02 LibraryGreen,Sunny,16°C,Moderate,Low,Traffic,Human voices,Wind,Trees,1,1,Many,Many,Some,Many,Very positive wellbeing,Easy,Very calm,Much more connected,Fallen leaves,Bags left outside library wall,0,1,Bags left outside library wall
42,R26_009,2026-09-22,L04 PathFrontiHub,Sunny,16°C,Loud,Low,Traffic,Human voices,Wind,Trees,0,1,Many,Some,Many,Many,Neutral,Slighly uneasy,Stressful,Less connected,More variety in planted shrubs,Loud traffic noise,0,2,Loud traffic noise
43,R26_009,2026-09-22,L05 GreenFrontSportsCentre,Sunny,17°C,Quiet,Low,Traffic,Human voices,Wind,Trees,5,0,Many,Many,Many,Many,Very positive wellbeing,Easy,Mostly calm,Much more connected,Little annoying bugs,Lots of dumped clothes,0,0,Lots of dumped clothes
44,R26_009,2026-09-22,L06 HedgingBehindSportsCentre,Sunny,15°C,Quiet,Low,Traffic,Construction,Trees,Seagulls,6,1,NaN,Some,Some,Many,Neutral,Neutral,Very calm,Much more connected,Lots of bushes,Yellow Golfball,0,0,Yellow Golfball
45,R26_010,2026-09-22,L01 MainEntrance,Partly Cloudy,17°C,Moderate,Low,Human voices,Traffic,Wind,Other birds,1,0,Many,Some,NaN,Some,Positive wellbeing,Easy,Mostly calm,A little more connected,Smoking people,NaN,1,1,0
46,R26_010,2026-09-22,L02 LibraryGreen,Partly Cloudy,17°C,Loud,Moderate,Traffic,Human voices,Wind,Wind,0,2,Many,Some,Many,Some,Positive wellbeing,Easy,Mostly calm,A little more connected,More birds,NaN,1,2,0
47,R26_010,2026-09-22,L04 PathFrontiHub,Partly Cloudy,17°C,Loud,Low,Traffic,Human voices,Wind,Insects,1,0,Many,Some,Many,Some,Positive wellbeing,Easy,Mostly calm,A little more connected,Spider,NaN,1,2,0
48,R26_010,2026-09-22,L05 GreenFrontSportsCentre,Partly Cloudy,17°C,Moderate,Low,Traffic,Traffic,Wind,Wind,0,0,Many,Some,Some,Some,Positive wellbeing,Easy,Mostly calm,A little more connected,Trafic sound,NaN,1,1,0
49,R26_010,2026-09-22,L06 HedgingBehindSportsCentre,Partly Cloudy,17°C,Quiet,Low,Traffic,Traffic,Wind,Wind,0,0,NaN,Some,NaN,Some,Positive wellbeing,Easy,Mostly calm,A little more connected,crab apple,NaN,1,0,0
50,R26_011,2026-09-22,L01 MainEntrance,Partly Cloudy,17°C,Loud,High,Human voices,Traffic,Wind,Other birds,1,2,Many,Many,NaN,Some,Positive wellbeing,Easy,Very calm,No change,Trees,Smoking,1,2,Smoking
51,R26_011,2026-09-22,L02 LibraryGreen,Partly Cloudy,16°C,Loud,Moderate,Traffic,Human voices,Other birds,Trees,4,2,Many,Some,NaN,Some,Positive wellbeing,Easy,Mostly calm,Less connected,Grass,NaN,1,2,0
52,R26_011,2026-09-22,L03 LowerSidePathiHub,Partly Cloudy,17°C,Quiet,Low,Human voices,Traffic,Seagulls,Wind,0,2,One or two,Some,Many,Some,Positive wellbeing,Easy,Very calm,No change,Flowerbed,NaN,1,0,0
53,R26_011,2026-09-22,L05 GreenFrontSportsCentre,Partly Cloudy,17°C,Moderate,Low,Traffic,Human voices,Trees,Wind,3,1,Many,Many,Some,NaN,Positive wellbeing,Easy,Very calm,No change,Wildflower area,pathway,1,1,pathway
54,R26_011,2026-09-22,L06 HedgingBehindSportsCentre,Partly Cloudy,17°C,Quiet,Low,Other,Human voices,Other birds,Trees,1,2,Many,Some,Many,NaN,Positive wellbeing,Easy,Very calm,No change,Bush,gunshots,1,0,gunshots
55,R26_012,2026-09-22,L05 GreenFrontSportsCentre,Sunny,18°C,Moderate,Low,Traffic,Other,Other,Wind,20,0,Many,Many,NaN,Some,Neutral,Neutral,Neutral,Less connected,some sort of a falcon,NaN,0,1,0
56,R26_012,2026-09-22,L02 LibraryGreen,Sunny,17°C,Loud,Moderate,Traffic,Human voices,Other birds,Other birds,0,10,Many,NaN,Some,Many,Positive wellbeing,Easy,Mostly calm,No change,"Birds, Trees",Construction site,0,2,Construction site
57,R26_012,2026-09-22,L06 HedgingBehindSportsCentre,Cloudy,13°C,Quiet,Low,Construction,Traffic,Other birds,Trees,10,5,Many,Some,NaN,NaN,Very positive wellbeing,Vey easy,Very calm,No change,"Trees, bushes",People,2,0,People
58,R26_012,2026-09-22,L01 MainEntrance,Sunny,17°C,Loud,High,Human voices,Traffic,Other birds,Wind,0,5,Many,NaN,Some,Many,Very positive wellbeing,Vey easy,Mostly calm,No change,"Trees, birds, wind sound",People smoking,0,2,People smoking
59,R26_013,2026-09-22,L01 MainEntrance,Sunny,16°C,Moderate,High,Human voices,Traffic,Wind,Trees,0,3,Many,Some,NaN,NaN,Positive wellbeing,Neutral,Very calm,No change,Leaves,NaN,0,1,0
60,R26_013,2026-09-22,L02 LibraryGreen,Sunny,17°C,Quiet,Low,Traffic,Human voices,Wind,Trees,1,0,Many,Many,Some,Many,Positive wellbeing,Vey easy,Very calm,Much more connected,Moss,NaN,0,0,0
61,R26_013,2026-09-22,L04 PathFrontiHub,Sunny,16.5°C,Moderate,Low,Traffic,Human voices,Wind,Other birds,1,1,Many,Some,Some,Many,Positive wellbeing,Slighly uneasy,Stressful,Less connected,Wind,NaN,0,1,0
62,R26_013,2026-09-22,L05 GreenFrontSportsCentre,Sunny,18°C,Quiet,Low,Traffic,Human voices,Wind,Other birds,1,2,Many,Many,Some,Many,Positive wellbeing,Easy,Mostly calm,A little more connected,Wind,NaN,0,0,0
63,R26_013,2026-09-22,L06 HedgingBehindSportsCentre,Sunny,14°C,Quiet,Low,Traffic,Human voices,Wind,Seagulls,3,3,NaN,Many,Many,Some,Positive wellbeing,Easy,Neutral,A little more connected,Seaguls,NaN,0,0,0
64,R26_014,2026-09-22,L04 PathFrontiHub,Sunny,18°C,Loud,Moderate,Traffic,Human voices,Trees,Wind,0,3,Many,NaN,Many,NaN,Neutral,Easy,Neutral,Less connected,Trees,NaN,0,2,0
65,R26_014,2026-09-22,L05 GreenFrontSportsCentre,Sunny,18°C,Moderate,Low,Traffic,Human voices,Seagulls,Trees,0,0,Many,Some,Some,Some,Positive wellbeing,Neutral,Neutral,Much more connected,Uncut Grass,NaN,0,1,0
69,R26_015,2026-09-23,L02 LibraryGreen,Sunny,18°C,Moderate,Moderate,Traffic,Human voices,Other birds,Wind,0,1,Many,Some,Some,Some,Positive wellbeing,Easy,Mostly calm,No change,"Trees, birds, wind sound",gardai,0,1,gardai
70,R26_015,2026-09-23,L04 PathFrontiHub,Sunny,17°C,Loud,High,Traffic,Human voices,Wind,Trees,1,0,Many,Some,Some,Many,Positive wellbeing,Easy,Mostly calm,No change,"Trees, bushes",fumes,0,2,fumes
71,R26_015,2026-09-23,L05 GreenFrontSportsCentre,Sunny,17°C,Moderate,Low,Traffic,Human voices,Wind,Trees,0,3,Many,Many,Some,NaN,Positive wellbeing,Easy,Mostly calm,A little more connected,trees,NaN,0,1,0
72,R26_015,2026-09-23,L06 HedgingBehindSportsCentre,Sunny,17°C,Quiet,Low,Human voices,Traffic,Other birds,Trees,0,0,Many,Many,Many,NaN,Positive wellbeing,Neutral,Very calm,No change,Grass,chair noises in sports hall,0,0,chair noises in sports hall
73,R26_015,2026-09-23,L07 CarParkNearSportsCentre,Sunny,17°C,Quiet,Low,Other,Human voices,Wind,Trees,3,1,Many,Many,Some,Many,Neutral,Easy,Mostly calm,Less connected,"Trees, birds, wind sound",machinery,0,0,machinery
74,R26_016,2026-09-23,L02 LibraryGreen,Sunny,17°C,Moderate,High,Traffic,Other,Wind,Insects,0,0,Many,Some,Some,Some,Neutral,Neutral,Neutral,same,Trees and Grass,NaN,0,1,0
75,R26_016,2026-09-23,L04 PathFrontiHub,Sunny,17°C,Loud,Moderate,Traffic,Human voices,Wind,Wind,0,0,Many,Some,Some,Many,Neutral,Neutral,Neutral,A little more connected,Trees and Grass,Traffic Volume highest here,0,2,Traffic Volume highest here
76,R26_016,2026-09-23,L05 GreenFrontSportsCentre,Sunny,17°C,Moderate,Low,Traffic,Human voices,Trees,Insects,2,3,Many,Many,Some,NaN,Neutral,Easy,Very calm,A little more connected,Trees and Grass,NaN,0,1,0
77,R26_016,2026-09-23,L06 HedgingBehindSportsCentre,Sunny,17°C,Quiet,Low,Human voices,Other,Trees,Other birds,0,0,Many,Some,Some,NaN,Positive wellbeing,Easy,Very calm,A little more connected,NaN,NaN,0,0,0
78,R26_016,2026-09-23,L07 CarParkNearSportsCentre,Sunny,17°C,Quiet,Low,Other,Other,Wind,Wind,3,1,Many,Some,Some,Some,Neutral,Neutral,Neutral,Less connected,NaN,Teleporter and lots of cars (Parking lot),0,0,Teleporter and lots of cars (Parking lot)
79,R26_017,2026-09-23,L01 MainEntrance,Partly Cloudy,17°C,Quiet,Low,Traffic,Human voices,Wind,Other birds,1,0,Many,Many,Some,NaN,Positive wellbeing,Neutral,Mostly calm,No change,grass,a lot of wasp,1,0,a lot of wasp
80,R26_017,2026-09-23,L02 LibraryGreen,Partly Cloudy,17°C,Loud,High,Traffic,Human voices,Wind,Trees,0,0,Many,Many,Some,NaN,Neutral,Neutral,Neutral,A little more connected,trees,rocks on the floor,1,2,rocks on the floor
81,R26_017,2026-09-23,L07 CarParkNearSportsCentre,Partly Cloudy,17°C,Quiet,Low,Human voices,Service machinery,Wind,Other,1,0,Many,Some,Some,Some,Neutral,Neutral,Neutral,No change,Trees,a telehandler,1,0,a telehandler
82,R26_017,2026-09-23,L06 HedgingBehindSportsCentre,Partly Cloudy,17°C,Quiet,Low,Traffic,Service machinery,Insects,Wind,1,0,Many,Some,Some,NaN,Low wellbeing,Vey easy,Neutral,Less connected,ornamental plants,NaN,1,0,0
83,R26_017,2026-09-23,L04 PathFrontiHub,Partly Cloudy,17°C,Loud,High,Human voices,Human voices,Wind,Trees,1,0,Many,Many,Some,NaN,Neutral,Neutral,Neutral,Less connected,Trees and Grass,Berries on the bush,1,2,Berries on the bush
84,R26_018,2026-09-23,L05 GreenFrontSportsCentre,Partly Cloudy,17°C,Moderate,Low,Traffic,Human voices,Wind,Trees,0,3,Many,Many,Some,NaN,Neutral,Neutral,Neutral,A little more connected,Trees,Patio made for sitting and relaxing,1,1,Patio made for sitting and relaxing
85,R26_018,2026-09-23,L06 HedgingBehindSportsCentre,Sunny,16°C,Quiet,Low,Human voices,Other,Other birds,Trees,1,0,Many,Many,Many,Some,Neutral,Neutral,Neutral,No change,Spider and Shrubs,NaN,0,0,0
86,R26_018,2026-09-23,L07 CarParkNearSportsCentre,Partly Cloudy,16°C,Moderate,Low,Human voices,Other,Wind,Trees,3,1,Many,Some,Some,Some,Neutral,Neutral,Neutral,No change,Nothing worth noting,Teleporter and lots of cars (Parking lot),1,1,Teleporter and lots of cars (Parking lot)
87,R26_018,2026-09-23,L02 LibraryGreen,Partly Cloudy,17°C,Moderate,High,Human voices,Traffic,Other birds,Wind,0,0,Many,Some,Some,Some,Neutral,Neutral,Neutral,No change,Trees and Grass,Lot of people nd olice station,1,1,Lot of people nd olice station
88,R26_018,2026-09-23,L04 PathFrontiHub,Partly Cloudy,17°C,Moderate,Moderate,Human voices,Traffic,Wind,Trees,1,0,Many,Some,Some,Many,Neutral,Neutral,Neutral,No change,Trees,Traffic Volume highest here,1,1,Traffic Volume highest here
89,R26_019,2026-09-24,L04 PathFrontiHub,Sunny,17°C,Moderate,High,Traffic,Human voices,Wind,Trees,7,6,Many,Some,Some,Some,Positive wellbeing,Slighly uneasy,Neutral,A little more connected,Bugs,Lots of smokers/vapers,0,1,Lots of smokers/vapers
90,R26_019,2026-09-25,L03 LowerSidePathiHub,Sunny,17°C,Quiet,Low,Human voices,Traffic,Wind,Trees,1,0,Many,Many,Many,Some,Positive wellbeing,Easy,Neutral,A little more connected,Lots of weeds,No one around,0,0,No one around
91,R26_019,2026-09-26,L05 GreenFrontSportsCentre,Sunny,17°C,Quiet,Low,Traffic,Human voices,Trees,Wind,3,0,Many,Some,NaN,NaN,Very positive wellbeing,Vey easy,Very calm,Much more connected,Wild ladybug apppeared on me,Ants on my sheet,0,0,Ants on my sheet
92,R26_019,2026-09-27,L06 HedgingBehindSportsCentre,Sunny,17°C,Quiet,Low,Construction,Human voices,Wind,Trees,2,2,One or two,Some,Some,Some,Neutral,Slighly uneasy,Neutral,Much more connected,"Crabapple tree, apples sour",Lots of webs no spiders,0,0,Lots of webs no spiders